---
title: "Code of Conduct"
---

For any activity hosted by the UC Center of Excellence on UAS Safety, we expect participants to follow these rules.  This includes any in-person training, virtual events, online forums and participation on social media.

The UC Center of Excellence is dedicated to providing a harassment-free experience for everyone whether in physical or virtual spaces.  We do not tolerate harassment of community members or event participants in any form.  Participants violating these rules may be sanctioned or expelled from the event at the discretion of the UC Center of Excellence on UAS Safety and any event organizers.

Harassment includes offensive verbal comments related to gender, gender identity and expression, sexual orientation, disability, group status, physical appearance, body size, race, or religion. In addition, harassment includes the acts of deliberate intimidation, stalking, following, unwelcome photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.

If an event participant engages in harassing behavior, the UC Center of Excellence on UAS Safety or event organizers may take any action they deem appropriate, including warning the offender or expulsion from the event.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact us by email  at UASsafety@ucmerced.edu.  We will work with anyone who reports an issue and will work quickly to address the problem.