---
title: "Mission"
---

## Unmanned Aircraft Systems at the University of California

The **University of California Center of Excellence on Unmanned Aircraft System Safety** provides system-wide expertise, support, and training for regulatory compliance, risk management, and the safe operation of unmanned aircraft systems (UAS), commonly known as drones, across the University of California system. This covers all 10 UC campuses, UC Medical Centers, the Division of Agriculture and Natural Resources, the UC Natural Reserve System, UC Cooperative Extensions, and wherever UC conducts official business worldwide.

Since March 2016, the Center of UAS Safety has worked to develop effective safety and risk management strategies applicable to the wide variety of unmanned aircraft use and development in the UC system. Across the UC system, there are currently an estimated 300 active unmanned aircraft used by UC faculty, staff and students, and the number is growing daily. The UC UAS Policy was finalized in February 2018 to establish a standardized top-down management approach and to assign roles & responsibilities for oversight.

## Regulatory Compliance, Risk Management and Training

The Center is focused on the following goals: - Promote UAS Safety through the development of a UAS Safety Management System, a four-pillared approach of Safety Policy, Safety Risk Management, Safety Assurance, and Safety Promotion - Develop effective UAS policies that define the processes and organization structure for UAS operations - Systematic processes for assessing and managing UAS risk - Fleet management system to provide continued monitoring of UAS activity and risk - Communicate UAS regulations and provide training

The wide range of UAS activity by UC affiliates and visitors necessitates a holistic approach to safety. The four-pillared approach, encapsulated as the UAS Safety Management System, structures safety as a combination of multiple aspects. This systematic approach is the first to manage UAS activity at the size and magnitude of the University of California system. While other agencies consider unmanned aircraft an isolated risk, the University of California has incorporated UAS into its Enterprise Risk Management approach.

## Services provided by the Center of UAS Safety

As primarily a service-oriented unit, the Center of UAS Safety has a long list of services it provides to the UC system. Some examples include:

- Guidance on UAS laws and regulations
- Guidance on UAS usage on UC property
- Generation of UAS activity reports
- Fleet management system to monitor UAS conditions, pilot training, and flight operations
- Identification of legal flying sites
- Processing of authorization for UAS flight operations
- Training on emerging UAS challenges
- Safety training on UAS operations

For more information about the University of California Center of Excellence on Unmanned Aircraft System Safety, visit the webpage or contact the Center at UASSafety\@ucmerced.edu or (209) 201-2051.
